services:
  linkding:
    container_name: "${LD_CONTAINER_NAME}"
    image: changhui/linkding:latest-alpine
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - env
    restart: unless-stopped