name: build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}



      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3



      - name: Build latest-alpine
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            changhui/linkding:latest-alpine
            changhui/linkding:${{ env.VERSION }}-alpine
          target: linkding
          push: true

 

      - name: Build latest-plus-alpine
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            changhui/linkding:latest-plus-alpine
            changhui/linkding:${{ env.VERSION }}-plus-alpine
          target: linkding-plus
          push: true